#!/bin/bash

# Terminate any polybar process if it exists already
killall -q polybar

# Wait until the polybar process(ess) shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch polybar with hot reload
#polybar example -r &
polybar primary  -r -c ~/.config/polybar/config_learn.ini &
polybar primary  -c ~/.config/polybar/workspace.ini &
