#!/bin/zsh

notify-send -t 3000 "Playing Video" "$(xclip -o)";
# mpv --ytdl-format=bestvideo+bestaduio/best --fs --speed=1.0 --af=rubberband=pitch-scale=0.981818181818181 "$(xclip -o)"
mpv --ytdl-format=bestvideo+bestaduio/best --fs --speed=1.0 "$(xclip -o)"
